feat(Callouts): Callouts component.
Telefonica/mistica-ios pull request #126
Opened 2021-08-02 09:40 UTC by alexanegon

## *🎟️ Jira ticket*

[IOS-6808](https://jira.tid.es/browse/IOS-6808) Callouts component

## *🥅 What's the goal?*

Add a new component called Callout as defined by [Zepplin](https://zpl.io/a3EEv4l)

## *🚧 How do we do it*

Create Callout view which has horizontal Stackview where we insert the image view content, title&actions vertical Stackview and the close button.

## *🧪 How can I test this?*

Downloading the catalog and see the new component inside the Callout section.

## **📱 Demo**

https://user-images.githubusercontent.com/43632903/127840076-283129e9-5965-4094-a052-d315077ed3c2.mov

2021-08-03 08:54 UTC, victorpimentel submitted a review, later dismissed
![](https://i.pinimg.com/originals/f8/ce/39/f8ce39769359522e24a1f24055558f15.gif)

2021-08-03 08:54 UTC, victorpimentel commented on CONTRIBUTING.md
> +
This is no longer needed, right? It should just work with bundle exec fastlane setup

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Callout.swift
> +    static let cornerRadius = CGFloat(4)
I think we prefer this form:

```suggestion
    static let cornerRadius: CGFloat = 4
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Callout.swift
> +    private let calloutBaseView = CalloutTitleActions()
Weird, it should be better if these two views had a similar name, right? Specially since you have `calloutBaseView` and `calloutContentBase` too.

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Callout.swift
> +    private let calloutBaseView = CalloutTitleActions()
Actually... is this being used at all? I didn't find any use of this, you use `calloutContentBase.calloutBaseView` everywhere.

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/CalloutConfiguration.swift
> +    let descriptionTitle: String
This should be called:

```suggestion
    let description: String
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/CalloutConfiguration.swift
> +    ///   - subtitle: This must be always visible
```suggestion
    ///   - description: This must be always visible
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/CalloutConfiguration.swift
> +    public init(withDescription description: String, asset: CalloutAssetType = .none, title: String? = nil, actions: CalloutActions? = nil, canClose: Bool = false) {
```suggestion
    public init(asset: CalloutAssetType = .none, title: String? = nil, description: String, actions: CalloutActions? = nil, canClose: Bool = false) {
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/CalloutConfiguration.swift
> +        descriptionTitle = description
```suggestion
        self.description = description
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/CalloutConfiguration.swift
> +    ///   - style: We have different typologies for callouts, with action buttons, with title and description or just a description
This comment doesn't make sense, it should be about the asset parameter, right?

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutButtons.swift
> +            primaryActionHandler = primaryAction.tapHandler
We prefer name overloads:

```suggestion
        if let primaryButton = primaryButton {
            self.primaryButton.title = primaryButton.title
            self.primaryButton.loadingTitle = primaryButton.loadingTitle
            primaryActionHandler = primaryButton.tapHandler
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutButtons.swift
> +            secondaryActionHandler = secondaryAction.tapHandler
Same thing:

```suggestion
        if let secondaryButton = secondaryButton {
            self.secondaryButton.title = secondaryButton.title
            self.secondaryButton.loadingTitle = secondaryButton.loadingTitle
            secondaryActionHandler = secondaryButton.tapHandler
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutContentBase.swift
> +class CalloutContentBase: UIStackView {
Interesting to inherit UIStackView: is this common in Mistica? (Just curious)

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutContentBase.swift
> +    }
```suggestion
    var description: String? {
        get {
            calloutBaseView.contentView.description
        }
        set {
            calloutBaseView.contentView.description = newValue
        }
    }
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutContentBase.swift
> +        } else {}
```suggestion
        }
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutContentBase.swift
> +        case .primaryAndLink(primary: let primaryButton, link: let linkButton):
This is just personal preference, but you can avoid writing let twice and you can remove the labels so that it reads a bit more succinct:

```suggestion
        case let .primaryAndLink(primaryButton, linkButton):
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutTitleActions.swift
> +/// CardBase is where we will manage the messages and buttons view.
```suggestion
/// CalloutTitleActions is where we will manage the messages and buttons view.
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Internals/CalloutMessagesContent.swift
> +/// CalloutCommonContent is a custom UIStackView where we will have the message section
```suggestion
/// CalloutMessagesContent is a custom UIStackView where we will have the message section
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Model/CalloutAsset.swift
> +    static let iconOffset = CGFloat(5)
Same, although I don't know if we are using this convention in Mistica:

```suggestion
    static let iconSize: CGFloat = 24
    static let iconOffset: CGFloat = 5
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/Model/CalloutContentItem.swift
> +/// Implementing the Card layout using a UIStackView is complex because the UIStackView only allows
```suggestion
///
/// Implementing the Callout layout using a UIStackView is complex because the UIStackView only allows
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Source/Components/Callout/README.md
> +                                        canClose: false)
```suggestion
let configuration = CalloutConfiguration(asset: CalloutConfiguration.CalloutAssetType.none,
                                         title: nil,
                                         description: "This is a description",
                                         actions: nil,
                                         canClose: false)
```

2021-08-03 08:54 UTC, victorpimentel commented on Mistica/Tests/MisticaTests/UI/CalloutTests.swift
> +            title: "This is a tilte"
```suggestion
            title: "This is a title"
```

2021-08-03 08:54 UTC, victorpimentel commented on Package.swift
> +                "Fonts/README.md"
Thanks!

2021-08-03 08:56 UTC, yceballost requested changes
can you release a new version of catalog? The last version in appcenter is from 2 jul 11.3.0

2021-08-03 09:47 UTC, alexanegon commented on Mistica/Source/Components/Callout/Callout.swift
> +    private let calloutBaseView = CalloutTitleActions()
Yes, I forgot to clean this var :S

2021-08-03 09:57 UTC, alexanegon commented on Mistica/Source/Components/Callout/CalloutConfiguration.swift
> +    ///   - style: We have different typologies for callouts, with action buttons, with title and description or just a description
You are right, I forgot to update the comment. This is an old comment of an old constructor.

2021-08-03 09:59 UTC, alexanegon commented on Mistica/Source/Components/Callout/Internals/CalloutContentBase.swift
> +class CalloutContentBase: UIStackView {
Yes, CardBase for example inherits from StackView

2021-08-03 10:18 UTC, alexanegon commented on Mistica/Tests/MisticaTests/UI/CalloutTests.swift
> +            title: "This is a tilte"
Good catch!

2021-08-03 10:18 UTC, alexanegon commented on Package.swift
> +                "Fonts/README.md"
<img src="https://media.giphy.com/media/3osxYdek8wYWCOLgT6/giphy.gif"/>

2021-08-03 10:19 UTC, alexanegon commented
> can you release a new version of catalog? The last version in appcenter is from 2 jul 11.3.0

When this PR is integrated into the main branch we could generate a new release for Mistica Catalog

2021-08-03 12:08 UTC, victorpimentel submitted a review, later dismissed

2021-08-03 12:50 UTC, yceballost commented
> > can you release a new version of catalog? The last version in appcenter is from 2 jul 11.3.0
> 
> When this PR is integrated into the main branch we could generate a new release for Mistica Catalog

But I need catalog to review :(. Video is not enough for me, I like touch the component and make screenshot to compare with design

In other component PR a pre-release was build to test the component by design side

2021-08-04 09:52 UTC, yceballost approved these changes
lgtm! nice job! ✨

2021-08-04 11:08 UTC, merged

2021-09-14 08:33 UTC, tuentisre commented
:tada: This PR is included in version 11.4.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v11.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: