IOS-6320 Add test for Fonttoolkit
Telefonica/mistica-ios pull request #132
Opened 2021-09-06 13:56 UTC by jmbrocal

2021-09-06 15:27 UTC, victorpimentel requested changes

2021-09-06 15:27 UTC, victorpimentel commented on Mistica/Tests/MisticaTests/Fonts/FontToolkitTests.swift
> +final class FontToolkitests: XCTestCase {
```suggestion
final class FontToolkitTests: XCTestCase {
```

2021-09-08 07:14 UTC, pbartolome approved these changes

2021-09-08 12:54 UTC, victorpimentel submitted a review, later dismissed

2021-09-08 12:54 UTC, victorpimentel commented on Mistica/Tests/MisticaTests/Fonts/FontToolkitTests.swift
> +private extension FontToolkitests {
```suggestion
private extension FontToolkitTests {
```

2021-09-09 10:13 UTC, pbartolome approved these changes

2021-09-10 09:49 UTC, victorpimentel approved these changes

2021-09-10 09:50 UTC, merged

2021-09-14 08:33 UTC, tuentisre commented
:tada: This PR is included in version 11.4.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v11.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: