Add error animation for feedback view for vivo
Telefonica/mistica-ios pull request #154
Opened 2022-01-17 16:27 UTC by Gomay88

Ticket -> https://jira.tid.es/browse/IOS-7087

**WHAT**
Need to add the error animation when displaying feedback error view

**HOW**
Added Movistar animation to vivo images and try the changes in MisticaCatalog

![vivo error](https://user-images.githubusercontent.com/16333047/149806134-290cf9c0-015a-4f14-bd41-106aea8e78dd.gif)

2022-01-18 09:16 UTC, yceballost commented
A designer as a reviewer is missing in this PR!!!!! :___(

2022-01-18 09:58 UTC, DavidMarinCalleja commented
> A designer as a reviewer is missing in this PR!!!!! :___(

you are right. @Gomay88  add to @yceballost  to this pr, please

2022-01-18 10:07 UTC, Gomay88 commented
> > A designer as a reviewer is missing in this PR!!!!! :___(
> 
> you are right. @Gomay88 add to @yceballost to this pr, please

I can't add him, when I search him in reviewers he doesn't appear

2022-01-19 08:59 UTC, jmpg93 approved these changes

2022-01-19 09:06 UTC, yceballost requested changes

2022-01-19 09:06 UTC, yceballost commented on Mistica/Source/Resources/Assets.xcassets/vivo/FeedbackError.dataset/Contents.json
> +{
Can you generate a version instead a video to review? I can't confirm if haptic feedback is working with the video, but If you can confirm this, I can approve this PR!

2022-01-19 09:44 UTC, alexanegon approved these changes
<img src="https://media.giphy.com/media/3osxYdek8wYWCOLgT6/giphy.gif"/>

2022-01-19 10:26 UTC, Gomay88 commented on Mistica/Source/Resources/Assets.xcassets/vivo/FeedbackError.dataset/Contents.json
> +{
You can try with the one I just generate. is the last one of Mistica catalog

2022-01-19 10:49 UTC, DavidMarinCalleja approved these changes
Good job!

2022-01-19 11:41 UTC, yceballost commented on Mistica/Source/Resources/Assets.xcassets/vivo/FeedbackError.dataset/Contents.json
> +{
works fine!

2022-01-19 11:42 UTC, yceballost approved these changes
gj! thanks!

2022-01-24 12:44 UTC, merged

2022-01-25 09:00 UTC, tuentisre commented
:tada: This PR is included in version 15.1.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v15.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: