feat(Feedback): IOS-7228 Updating feedback success/error lottie animations
Telefonica/mistica-ios pull request #164
Opened 2022-02-10 15:41 UTC by salavert

### Update feedbacks icons animation (in O2)
https://jira.tid.es/browse/IOS-7228

### Success and error icons for O2
https://github.com/Telefonica/mistica-icons/tree/production/animated-icons/O2

### Proof of fix

<img src="https://user-images.githubusercontent.com/216846/153441999-573d8d14-2745-43c5-af0a-b74755e8a95f.gif" width=300 />

2022-02-14 07:52 UTC, DavidMarinCalleja requested changes
it looks like the tests need to be updated

2022-02-14 14:33 UTC, pbartolome approved these changes

2022-02-14 14:52 UTC, salavert reviewed
Fixed

2022-02-15 07:01 UTC, DavidMarinCalleja approved these changes

2022-02-15 09:16 UTC, merged

2022-02-15 09:18 UTC, tuentisre commented
:tada: This PR is included in version 15.2.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v15.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: