IOS-7624 Add bottom sheet component in Mistica and Catalog
Telefonica/mistica-ios pull request #214
Opened 2022-09-09 07:35 UTC by alejandroruizponce

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-7624

## 🥅 **What's the goal?**
Add a generic component to display a bottom sheet selector. At the moment the needs of this bottom sheet are the following:
- It is only a list with rows with text and radioButton.
- It is auto-submittable by clicking on one of the choices or dismisse it.
- It is a single selection.

More information in this Figma link:
https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/%5BWIP%5D-Sheet?node-id=804%3A13588

In next iterations the idea is to extend it to be able to receive more types of content like buttons, or more than one list. For now the component must be basic and contemplate a single scenario.

## 🚧 **How do we do it?**
The following has been implemented for this purpose:
- BottomSheetView for visual layouts and BottomSheetViewController to display it.
- SheetTransitionDelegate and SheetPresentation for the way to display it on the screen, using fluid transition.
- Added to the catalog for testing.

## 🧪 **How can I verify this?**
Use Mistica Catalog and select the Bottom Sheet component for testing.

2022-09-12 16:02 UTC, yceballost commented
Can you release a version of the catalog to try the component and review it? thanks!

2022-09-13 09:50 UTC, alexanegon reviewed
Issues founded:

1. In the Figma file the asset is aligned with the top of the title.
2. In the catalog app, could we make the description of the elements optional to see the result? It seems that the 24px margin between the title and the row is not like in the Figma section "Contenido configurable"
 <img src="https://user-images.githubusercontent.com/43632903/189869970-e823edbd-20a5-4c7b-8bc6-66376d7a55cf.png" width=25% height=25%>

3. Check constraints

`2022-09-13 11:21:11.952379+0200 MisticaCatalog[10592:153084] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000010e84b0 V:[UILabel:0x160fb9120]-(16)-[UIStackView:0x160f17500]   (active)>",
    "<NSLayoutConstraint:0x600001318190 'UISV-canvas-connection' V:[UILabel:0x160fb9120]-(0)-|   (active, names: '|':UIStackView:0x160fc7d10 )>",
    "<NSLayoutConstraint:0x600001305630 'UISV-spacing' V:[UIStackView:0x160fc7d10]-(0)-[UIStackView:0x160f17500]   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001318190 'UISV-canvas-connection' V:[UILabel:0x160fb9120]-(0)-|   (active, names: '|':UIStackView:0x160fc7d10 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.`

2022-09-13 09:50 UTC, alexanegon commented on Sources/Mistica/Components/BottomSheet/BottomSheet/SheetPresentationController.swift
> +    }
Maybe we can add private functions to a private extension. WDYT?

2022-09-13 09:50 UTC, alexanegon commented on Sources/Mistica/Components/BottomSheet/BottomSheet/SheetTransition.swift
> +    private func presentationInterruptibleAnimator(using transitionContext: UIViewControllerContextTransitioning) -> UIViewImplicitlyAnimating {
I would separate private functions into a private extension

2022-09-13 09:50 UTC, alexanegon commented on Sources/Mistica/Components/BottomSheet/Model/BottomSheetSelectionResponse.swift
> +public enum BottomSheetActionResponse: String {
Which are the differences between dismissing and submit?

2022-09-14 15:16 UTC, alejandroruizponce commented on Sources/Mistica/Components/BottomSheet/Model/BottomSheetSelectionResponse.swift
> +public enum BottomSheetActionResponse: String {
DISMISS is when you tap outside for example but you didn't select any option. You must send anyway the initial selected option as response. And submit, for now, is when you select an option manually and the sheet is dismissed.

2022-09-14 15:20 UTC, alejandroruizponce commented on Sources/Mistica/Components/BottomSheet/BottomSheet/SheetPresentationController.swift
> +    }
Yes, fixed!

2022-09-14 15:20 UTC, alejandroruizponce commented on Sources/Mistica/Components/BottomSheet/BottomSheet/SheetTransition.swift
> +    private func presentationInterruptibleAnimator(using transitionContext: UIViewControllerContextTransitioning) -> UIViewImplicitlyAnimating {
Yes, fixed!

2022-09-14 16:43 UTC, yceballost requested changes

2022-09-14 16:43 UTC, yceballost commented on Sources/Mistica/Components/BottomSheet/View/BottomSheetView.swift
> +//
Design review
https://telefonicacorp-my.sharepoint.com/:w:/g/personal/ignacio_ceballostorres_telefonica_com/ETSEHJLlQChPv4cXz9-4CnYBoqLx3xZ6NxjpIKinK3UQ6Q?e=qYd3F9

2022-09-14 16:43 UTC, yceballost commented on Sources/Mistica/Components/BottomSheet/BottomSheet/SheetTransition.swift
> +    private let animationDuration: TimeInterval = 0.75
```suggestion
    private let animationDuration: TimeInterval = 0.5
```

2022-09-15 06:38 UTC, alexanegon commented on Sources/Mistica/Components/BottomSheet/Model/BottomSheetSelectionResponse.swift
> +public enum BottomSheetActionResponse: String {
Nice, maybe we can set this explanation as a comment of the enum. WDYT?

2022-09-15 07:22 UTC, jmpg93 commented
Hi! I'm missing a few points of this list: https://github.com/Telefonica/mistica-ios/blob/main/CONTRIBUTING.md#how-to-work-with-mistica-ios like tests or documentation.

Also, did you consider accessibility?

2022-09-15 16:11 UTC, yceballost submitted a review, later dismissed
brilliant ✨

2022-09-15 18:24 UTC, yceballost requested changes

2022-09-15 18:24 UTC, yceballost commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        overlayView.fade(toAlpha: 0.5, duration: 0.25)
```suggestion
        overlayView.fade(toAlpha: 1, duration: 0.25)
```

`backgroundOverlay` has its own opacity I think you are applying opacity over the `backgroundOverlay` opacity, I think this value has to be `1` (or maybe remove?)

https://github.com/Telefonica/mistica-ios/blob/4d64130039f83128b8305012ce35575294c720a6/Sources/MisticaCommon/Colors/MovistarColorPalette.swift#L19

2022-09-16 06:08 UTC, alexanegon commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +        ])
Please, check the constraints since the console is warning us:

2022-09-16 08:03:46.894152+0200 MisticaCatalog[73184:2307474] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000003863a0 UIStackView:0x14ee64130.width == UIStackView:0x14ee62730.width   (active)>",
    "<NSLayoutConstraint:0x6000003b4960 'UISV-alignment' UIStackView:0x14ee628c0.leading == UIStackView:0x14ee63fa0.leading   (active)>",
    "<NSLayoutConstraint:0x6000003bc780 'UISV-canvas-connection' UIStackView:0x14ee63fa0.leading == UIStackView:0x14ee64130.leading   (active)>",
    "<NSLayoutConstraint:0x6000003bc6e0 'UISV-canvas-connection' H:[Mistica.RadioButton:0x14ee64d30]-(0)-|   (active, names: '|':UIStackView:0x14ee63fa0 )>",
    "<NSLayoutConstraint:0x6000003b4370 'UISV-canvas-connection' UIStackView:0x14ee62730.leading == UIStackView:0x14ee628c0.leading   (active)>",
    "<NSLayoutConstraint:0x6000003b4820 'UISV-canvas-connection' H:[_UILayoutSpacer:0x600001fcb0c0'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x14ee62730 )>",
    "<NSLayoutConstraint:0x6000003bd220 'UISV-spacing' H:[UIStackView:0x14ee64130]-(16)-[Mistica.RadioButton:0x14ee64d30]   (active)>",
    "<NSLayoutConstraint:0x6000003b45f0 'UISV-spanning-boundary' _UILayoutSpacer:0x600001fcb0c0'UISV-alignment-spanner'.trailing >= UIStackView:0x14ee63fa0.trailing   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000003bd220 'UISV-spacing' H:[UIStackView:0x14ee64130]-(16)-[Mistica.RadioButton:0x14ee64d30]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-09-16 08:03:46.895080+0200 MisticaCatalog[73184:2307474] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000003f2940 UIStackView:0x14ee62a50.width == UIStackView:0x14ee62730.width   (active)>",
    "<NSLayoutConstraint:0x6000003a9900 'UISV-canvas-connection' UIStackView:0x14ee628c0.leading == UIStackView:0x14ee62a50.leading   (active)>",
    "<NSLayoutConstraint:0x6000003a9ea0 'UISV-canvas-connection' H:[Mistica.RadioButton:0x14ee63650]-(0)-|   (active, names: '|':UIStackView:0x14ee628c0 )>",
    "<NSLayoutConstraint:0x6000003b4370 'UISV-canvas-connection' UIStackView:0x14ee62730.leading == UIStackView:0x14ee628c0.leading   (active)>",
    "<NSLayoutConstraint:0x6000003b4820 'UISV-canvas-connection' H:[_UILayoutSpacer:0x600001fcb0c0'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x14ee62730 )>",
    "<NSLayoutConstraint:0x6000003aa300 'UISV-spacing' H:[UIStackView:0x14ee62a50]-(16)-[Mistica.RadioButton:0x14ee63650]   (active)>",
    "<NSLayoutConstraint:0x6000003b44b0 'UISV-spanning-boundary' _UILayoutSpacer:0x600001fcb0c0'UISV-alignment-spanner'.trailing >= UIStackView:0x14ee628c0.trailing   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000003aa300 'UISV-spacing' H:[UIStackView:0x14ee62a50]-(16)-[Mistica.RadioButton:0x14ee63650]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-09-16 08:03:46.914017+0200 MisticaCatalog[73184:2307474] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000039c230 UIStackView:0x14ee65610.width == UIStackView:0x14ee62730.width   (active)>",
    "<NSLayoutConstraint:0x6000003b4aa0 'UISV-alignment' UIStackView:0x14ee628c0.leading == UIStackView:0x14ee65480.leading   (active)>",
    "<NSLayoutConstraint:0x6000003b9cc0 'UISV-canvas-connection' UIStackView:0x14ee65480.leading == UIStackView:0x14ee65610.leading   (active)>",
    "<NSLayoutConstraint:0x6000003b9c70 'UISV-canvas-connection' H:[Mistica.RadioButton:0x14ee66210]-(0)-|   (active, names: '|':UIStackView:0x14ee65480 )>",
    "<NSLayoutConstraint:0x6000003b4370 'UISV-canvas-connection' UIStackView:0x14ee62730.leading == UIStackView:0x14ee628c0.leading   (active)>",
    "<NSLayoutConstraint:0x6000003b4820 'UISV-canvas-connection' H:[_UILayoutSpacer:0x600001fcb0c0'UISV-alignment-spanner']-(0)-|   (active, names: '|':UIStackView:0x14ee62730 )>",
    "<NSLayoutConstraint:0x6000003b9bd0 'UISV-spacing' H:[UIStackView:0x14ee65610]-(16)-[Mistica.RadioButton:0x14ee66210]   (active)>",
    "<NSLayoutConstraint:0x6000003b4780 'UISV-spanning-boundary' _UILayoutSpacer:0x600001fcb0c0'UISV-alignment-spanner'.trailing >= UIStackView:0x14ee65480.trailing   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000003b9bd0 'UISV-spacing' H:[UIStackView:0x14ee65610]-(16)-[Mistica.RadioButton:0x14ee66210]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

2022-09-16 06:08 UTC, alexanegon commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +class UICatalogSheetViewController: UIViewController {
Same as you added the capability to show or hide the asset in the items, I would add the capability to hide the description.

2022-09-16 06:52 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        overlayView.fade(toAlpha: 0.5, duration: 0.25)
Yes, you're right, fixed!

2022-09-16 06:52 UTC, alejandroruizponce commented on MisticaCatalog/Source/Assets.xcassets/Rows/Sheets.imageset/Contents.json
> +      "filename" : "Bottom Sheets.svg",
Fixed!

2022-09-16 06:52 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        }
Fixed!

2022-09-16 06:52 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        )
Ok, Fixed!

2022-09-16 06:52 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        let content: SheetList = .init(
Fixed!

2022-09-16 06:53 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        let viewController = SheetViewController(configuration: configuration) { _ in }
Ok, added!

2022-09-16 06:53 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +    }
Nope, removed.

2022-09-16 06:53 UTC, alejandroruizponce commented on MisticaCatalog/Source/Common/Views/UIStepperTableViewCell.swift
> +    public var didValueChange: ((UIStepper) -> Void)?
Removed!

2022-09-16 06:53 UTC, alejandroruizponce commented on MisticaCatalog/Source/Common/Views/UIStepperTableViewCell.swift
> +    }
Fixed!

2022-09-16 06:53 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
> +    public var content: [SheetList]
Fixed!

2022-09-16 06:53 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
> +    public var description: String?
Fixed!

2022-09-16 06:53 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
> +    public var items: [SheetListRow]
Fixed!

2022-09-16 06:53 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
> +    public var isSelected: Bool
Fixed!

2022-09-16 06:53 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetSelectionResponse.swift
> +public enum SheetActionResponse: String {
Commented!

2022-09-16 06:53 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetSelectionResponse.swift
> +    public var selectedIds: [SheetResponseResult]
Fixed!

2022-09-16 06:54 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/Model/SheetSelectionResponse.swift
> +    public let selected: [String]
Fixed!

2022-09-16 06:54 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +        ])
I do not see these logs when displaying the sheet in either Catalog or Novum. There are no warnings in my debug.

2022-09-16 06:55 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +class UICatalogSheetViewController: UIViewController {
For the next iteration we will add the config to edit the rows.

2022-09-16 07:08 UTC, yceballost approved these changes

2022-09-16 07:24 UTC, jmpg93 commented on MisticaCatalog/Source/Common/Views/UIStepperTableViewCell.swift
> +public class UIStepperTableViewCell: UITableViewCell {
Drop the UI prefix please.

2022-09-16 07:25 UTC, alexanegon commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +        ])
@jmpg93 do you see those logs?

2022-09-16 07:26 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
> +    let description: String?
Are all three texts optional? What if we make the title non-optional and make the whole `Section` optional? So you don't have to build an empty section to create a `SheetConfiguration`?

```
let configuration = SheetConfiguration(header: nil, content: [])
vs
let configuration = SheetConfiguration(header: Section(), content: [])
```

2022-09-16 07:28 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        /// The maximum height allowed for the sheet. We allow the sheet to reach the top safe area inset.
Comments that are not documentation should use `//` instead of `///`

2022-09-16 07:47 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +    private var contentInfo: [String: [String: RadioButton]] = [:]
What is this content info? Can't we use a struct os something like that?

2022-09-16 07:49 UTC, alexanegon submitted a review, later dismissed

2022-09-16 07:51 UTC, yceballost approved these changes

2022-09-16 08:26 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/Model/SheetSelectionResponse.swift
> +    case submit = "SUBMIT"
Do you really need this to have a string value?

2022-09-16 08:28 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +    public var dismissSheet: (() -> Void)?
I would have made this to return the response.
dismissSheet: (SheetResponse) -> Void

2022-09-16 08:31 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +                itemStackView.addGestureRecognizer(itemTapGesture)
Instead of creating all the elements on appear, we could have use a list with reusable Cells. A mistica Cell can be easily configured as the rows of the sheet.

2022-09-16 08:31 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/SheetView.swift
> +                radioButton.widthAnchor.constraint(equalToConstant: 20.0).isActive = true
I think the radio button doesn't need constraints.

2022-09-16 08:34 UTC, jmpg93 commented
I'm still missing tests and the SwiftUI implementation.

2022-09-16 09:32 UTC, amegias commented on Makefile
> +export DEVELOPER_DIR=/Applications/Xcode-13.4.1.app/Contents/Developer
it's wrong @alejandroruizponce

2022-09-16 09:38 UTC, amegias approved these changes

2022-09-16 09:42 UTC, amegias approved these changes

2022-09-16 09:44 UTC, merged

2022-09-16 09:45 UTC, jmpg93 commented
Please, if you are going to merge this branch because we need the changes for 13.8, create ticket with the following:
- Implemente SwiftUI version
- Add snapshot test.
- Try to simplify the setup of the sheet: it is hard to follow the view definition with all that constraints.
- Replace doc slashes with comment slashes

2022-09-16 10:07 UTC, tuentisre commented
:tada: This PR is included in version 18.1.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v18.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: