IOS-7731 Fix Sheet component with dismissal bug
Telefonica/mistica-ios pull request #225
Opened 2022-10-04 12:05 UTC by alejandroruizponce

Hi there!

This PR has several objectives that are linked to each other:
- Fix the dismissal bug when we drag down a bit with the Sheet. Taking as reference the Novum code I have been able to refactor my transitions delegate so that it works properly in all cases. It will be necessary to add that delegate to the Novum code as well so that everything works correctly.
- This refactor has entailed some modifications in the Sheet view as well as a cleaning and reordering of the code.
- Having modified the view and the way of instantiating it, I have preferred to unify in this PR the UI tests, since those of the previous PR would have been obsolete for the new view.

Regarding the latter, the UI tests still fail when they take a new snapshot, for some reason each snapshot is different from the previous one, it is never the same.

2022-10-04 14:40 UTC, amegias commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                }
why is it needed??? This delay is ugly...

https://user-images.githubusercontent.com/9945756/193849381-39fb30e3-3dcf-4758-88bf-5f8b175df12e.mov

2022-10-04 14:43 UTC, amegias commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +            item.isActivated = true
```suggestion
            content.forEach { $1.isActivated = $1 == item }
```

2022-10-04 14:50 UTC, amegias submitted a review, later dismissed
Really good job, Álex!!!!!
Thanks for taking care of the component :)

2022-10-05 08:19 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                }
I think that at the UX level a little delay is nice, so that the user can see which option has been selected before dismiss it. I have reduced it to 0.25, I think it looks better now.

2022-10-05 08:20 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +            item.isActivated = true
You're very right! Thanks!

2022-10-05 08:22 UTC, amegias approved these changes

2022-10-05 08:52 UTC, amegias approved these changes

2022-10-05 09:59 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                }
I agree with @amegias this delay is ugly for me too. This kind of decision must be defined by UX/UI team.

2022-10-05 10:01 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        let viewController = SheetViewController(configuration: configuration, completionHandler: { sheetResponse in
why do we need this change? is it due swift format?

2022-10-05 10:02 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        return subtitle
The same than above

2022-10-05 10:02 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        return description
The same than above

2022-10-05 10:11 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        safeTopInset = containerView?.safeAreaInsets.top ?? 0
```suggestion
        let safeTopInset: CGFloat = containerView?.safeAreaInsets.top ?? 0
```

I am not sure if we need the type here.

2022-10-05 10:14 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +            animation()
Why do we need this function? The presentedViewController is the sheet and the we always set a transition coordinator, maybe here we should add a guard with an log message or fatal error?

2022-10-05 10:14 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetTransitioningDelegate.swift
> +public class SheetTransitioningDelegate: NSObject {
Need to be public?

2022-10-05 10:16 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetTransitioningDelegate.swift
> +        viewController.dismiss(animated: true, completion: nil)
Should we set to false `isInteractionInProgress` when the completion block is called?

2022-10-05 10:51 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        dimmingView.accessibilityIdentifier = "dimmingView"
Are we using this identifier?

2022-10-05 10:53 UTC, jmbrocal commented on Tests/MisticaTests/UI/SheetTests.swift
> +        }
This code is repeated in other tests, maybe you can create an AnyValues enum and adding this there to be reused

2022-10-05 10:54 UTC, jmbrocal commented on Tests/MisticaTests/UI/SheetTests.swift
> +        }
This code is repeated in other tests, maybe you can create an AnyValues enum and adding this there to be reused

2022-10-05 10:54 UTC, jmbrocal commented on Tests/MisticaTests/UI/SheetTests.swift
> +        )
The same for this content

2022-10-05 11:26 UTC, jmbrocal commented on Tests/MisticaTests/UI/SheetTests.swift
> +    }
This test is not needed because the component does not allow this case.

2022-10-05 11:42 UTC, jmbrocal commented on Tests/MisticaTests/UI/SheetTests.swift
> +final class SheetTests: XCTestCase {
IMO this tests are not correct because they are testing the component in isolation but this component is never used alone. It is always shown over a view. The following points of the component are not being tested
- the dimmed view
- the component height based on the content

I think we should use a more real example, with a dummy view controller which is showing the sheet.

WDYT?

2022-10-05 12:01 UTC, jmbrocal commented
I found the following issues after testing the component
- It seems like the icons are downloaded in main thread, you can see the following logs
````
[CFNetwork] Synchronous URL loading of https://img.icons8.com/ios/344/bookmark--v1.png should not occur on this application's main thread as it may lead to UI unresponsiveness. Please switch to an asynchronous networking API such as URLSession.
````
<img width="1176" alt="Screen Shot 2022-10-05 at 13 56 30" src="https://user-images.githubusercontent.com/1420856/194054954-5138c231-7d20-4a50-8f92-614eb99d4116.png">

- When the component has no title or subtitle is not keeping the space the space of the title
current state
<img width="193" alt="Screen Shot 2022-10-05 at 13 48 35" src="https://user-images.githubusercontent.com/1420856/194053796-2f57bf99-58d9-400c-9451-14404f97684a.png">
Sample from spec
<img width="193" alt="Screen Shot 2022-10-05 at 13 48 35" src="https://user-images.githubusercontent.com/1420856/194053816-24a016b7-a4c0-497d-9ecd-f81f10cb455d.png">
- The dismiss animation when dismissing the sheet using a pan gesture is not fluid. the component moves down more slowly than my finger.

2022-10-05 13:09 UTC, amegias requested changes

2022-10-05 13:09 UTC, amegias commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                        imageView.image = lightImage
bad merge @alejandroruizponce.
as @jmbrocal said, it's wrong. It's already solved in main, so be careful since it looks an old version of the component....
Solved here: https://github.com/Telefonica/mistica-ios/pull/221

2022-10-07 10:15 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        let viewController = SheetViewController(configuration: configuration, completionHandler: { sheetResponse in
Nope, back and fixed!

2022-10-07 11:04 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        return title
It is a simple way to hide those labels in the view when they are null. What you say would also be valid.

2022-10-07 11:04 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        safeTopInset = containerView?.safeAreaInsets.top ?? 0
Yes, many lines. Fixed!

2022-10-07 11:05 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +            animation()
I think that returning a return if the coordinator is not present would make sense. It is consistent with the title of the function. Fixed!

2022-10-07 11:05 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetTransitioningDelegate.swift
> +public class SheetTransitioningDelegate: NSObject {
Yes, it has to be public in order to instantiate the delegate from outside.

2022-10-07 11:05 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetTransitioningDelegate.swift
> +        viewController.dismiss(animated: true, completion: nil)
It is set to false when dismiss ends.

2022-10-07 11:06 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> +        dimmingView.accessibilityIdentifier = "dimmingView"
Nope really, fixed.

2022-10-07 11:06 UTC, alejandroruizponce commented on Tests/MisticaTests/UI/SheetTests.swift
> +        }
Yes, you are right, I have created an auxiliary function to reuse code.

2022-10-07 11:06 UTC, alejandroruizponce commented on Tests/MisticaTests/UI/SheetTests.swift
> +    }
True, removed.

2022-10-07 11:07 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                        imageView.image = lightImage
Yes, it was a bad merge. Fixed now!

2022-10-07 11:10 UTC, alejandroruizponce commented on Tests/MisticaTests/UI/SheetTests.swift
> +final class SheetTests: XCTestCase {
This is something I discussed with @amegias when I did the first tests, but we discarded it because it involved complex changes and the delay of the Sheet animation in appearing gave problems to show it in a basic VC. The snapshot was always done before the Sheet was displayed.

2022-10-07 11:13 UTC, alejandroruizponce commented
> I found the following issues after testing the component
> 
> * It seems like the icons are downloaded in main thread, you can see the following logs
> 
> ```
> [CFNetwork] Synchronous URL loading of https://img.icons8.com/ios/344/bookmark--v1.png should not occur on this application's main thread as it may lead to UI unresponsiveness. Please switch to an asynchronous networking API such as URLSession.
> ```
> 
> <img alt="Screen Shot 2022-10-05 at 13 56 30" width="1176" src="https://user-images.githubusercontent.com/1420856/194054954-5138c231-7d20-4a50-8f92-614eb99d4116.png">
> 
> * When the component has no title or subtitle is not keeping the space of the title
>   current state
> 
> <img alt="Screen Shot 2022-10-05 at 13 48 35" width="193" src="https://user-images.githubusercontent.com/1420856/194053796-2f57bf99-58d9-400c-9451-14404f97684a.png">
> 
> Sample from spec
> <img alt="Screen Shot 2022-10-05 at 13 48 35" width="193" src="https://user-images.githubusercontent.com/1420856/194053816-24a016b7-a4c0-497d-9ecd-f81f10cb455d.png">
> 
> - The dismiss animation when dismissing the sheet using a pan gesture is not fluid. the component moves down more slowly than my finger.

When @yceballost  returns from holidays, it would be interesting to get his opinion on the title and the swipe animation. The first seems weird to me that you have to leave that space and the second, about swipe animation, is as it was in Novum animator.

2022-10-07 13:19 UTC, amegias approved these changes

2022-10-10 07:38 UTC, amegias commented on Tests/MisticaTests/UI/SheetTests.swift
> +final class SheetTests: XCTestCase {
AFAIK, we should add a host app to test presentations, etc with VC. So currently we are only able to test views (or static VControllers)

2022-10-10 09:18 UTC, jmbrocal commented on Tests/MisticaTests/UI/SheetTests.swift
> +final class SheetTests: XCTestCase {
But for ui testing we do not tests animations because we cant xD. My point is that testing this component using a dummy viewcontroller allows to tests it in deph.

Maybe you have to do some change in code so the component disable animations or makes it animates very fast, but I did it for other components with no issues.

I you were talked about this and decide to go with the proposed approach, I am ok, but IMHO we can do a better job when testing.

2022-10-11 10:36 UTC, yceballost approved these changes
like a charm✨

2022-10-11 15:37 UTC, merged

2022-10-11 15:39 UTC, tuentisre commented
:tada: This PR is included in version 18.2.4 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v18.2.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: