Ios 7746 bottom sheet v2
Telefonica/mistica-ios pull request #228
Opened 2022-10-20 11:50 UTC by jmbrocal

2022-10-20 12:57 UTC, alejandroruizponce requested changes

2022-10-20 12:57 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        cell.segmentedControl.insertSegment(withTitle: "default", at: 0, animated: false)
```suggestion
        cell.segmentedControl.insertSegment(withTitle: "Default", at: 0, animated: false)
```

2022-10-20 12:57 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        cell.segmentedControl.insertSegment(withTitle: "destructive", at: 1, animated: false)
```suggestion
        cell.segmentedControl.insertSegment(withTitle: "Destructive", at: 1, animated: false)
```

2022-10-20 12:57 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        cell.segmentedControl.insertSegment(withTitle: "bullet", at: 0, animated: false)
```suggestion
        cell.segmentedControl.insertSegment(withTitle: "Bullet", at: 0, animated: false)
```

2022-10-20 12:57 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        let icon: InformativeItemIcon
Are you not checking at any time whether the icon should be visible or not? It's always visible in Catalog for informative or action lists.

2022-10-20 12:57 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +                url: "https://img.icons8.com/ios-glyphs/344/bookmark.png",
Same here, icon has to be always visible in this list type? Here appears without icon:
https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/Sheet?node-id=1960%3A13985

2022-10-20 12:57 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/SheetTransition/SheetPresentationController.swift
> -        let maximumHeight = containerView.frame.height - containerView.safeAreaInsets.top - containerView.safeAreaInsets.bottom
Cool!

2022-10-20 12:57 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +        stackView.systemLayoutSizeFitting(
Good approach! But I find some issues in these cases:

11 action rows in sheet with title:
<img src="https://user-images.githubusercontent.com/23401607/196954090-b7fcad51-0d93-403e-889f-beec46d25c92.PNG" width="200">

11 action rows without title:
<img src="https://user-images.githubusercontent.com/23401607/196954099-6acf3784-b3bd-412c-a09d-a16ca3e6d1f3.PNG" width="200">

2022-10-20 13:03 UTC, alejandroruizponce commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                sheetSelectionResponse = .init(action: .submit, selectedIds: [])
Mm, maybe it comes in the documentation but I have not seen it, when taping in a row informative type, the idea is that we do not return that id row selected or anything? Only we dismiss the sheet? And if so, when testing I have seen that the action that is sent is SUBMIT instead of DISMISS. Is this correct?

2022-10-20 13:27 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        cell.segmentedControl.insertSegment(withTitle: "bullet", at: 0, animated: false)
Fixed this and other segments

2022-10-20 13:28 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        cell.segmentedControl.insertSegment(withTitle: "destructive", at: 1, animated: false)
done here and other segment

2022-10-20 13:29 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +                url: "https://img.icons8.com/ios-glyphs/344/bookmark.png",
Nop, we support actions without images. I will refactor this screen in other PR. Ty

2022-10-20 13:31 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                sheetSelectionResponse = .init(action: .submit, selectedIds: [])
About the selection: yes. For informative type we do not return the row tapped. About the submit or dismiss, I am not sure but I will check it with android.

2022-10-20 13:32 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +        stackView.systemLayoutSizeFitting(
The whole structure of this component is really hard to follow... I will investigate this case...

2022-10-20 13:34 UTC, jmbrocal commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +        let icon: InformativeItemIcon
Informative always has icons while actions can be displayed without icons.

2022-10-20 13:38 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/ActionRow.swift
> +class ActionRow: UIStackView {
Minor, but this is the only view that inherits from `UIStackView` even tho every other one is also using `UIStackView` as the primary content view.

2022-10-20 13:39 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/InformativeRow.swift
> +        dummyView.backgroundColor = .red
We don't need this.
```suggestion
```

2022-10-20 13:40 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/SingleSelectionRow.swift
> +    func setUp() {
```suggestion
        commonInit()
    }

    @available(*, unavailable)
    required init(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

extension SingleSelectionRowView {
    var isSelected: Bool {
        get {
            radioButton.isActivated
        }
        set {
            radioButton.isActivated = newValue
        }
    }
}

private extension SingleSelectionRowView {
    func commonInit() {
```

2022-10-20 13:43 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> -        scrollHeight.isActive = true
The height of the sheet is now fully manageb by the presentation controller.

2022-10-20 13:46 UTC, jmpg93 commented on Sources/Mistica/Utils/Views/ScrollStackView.swift
> +    }
I think we can remove this. I created the `FittingCompressedScrollStackView` to avoid impacting other views.

2022-10-20 13:47 UTC, jmpg93 commented on Tests/MisticaTests/UI/FeedbackTests.swift
> +            as: .image,
Why did you change this?

2022-10-20 13:50 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +                sheetSelectionResponse = .init(action: .submit, selectedIds: [])
I updated the PR, now for the informative type the library returns action == dismiss. Ty!

2022-10-20 13:52 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/ActionRow.swift
> +class ActionRow: UIStackView {
Yep, it was intentionally. The Action row is the most simple one so I just inherit from UIStackView so the view stack is more flattern

2022-10-20 14:21 UTC, aweell commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/InformativeRow.swift
> +            imageView.image = UIImage.circle(diameter: 6, color: .neutralHigh)
It seems that the bullet diameter is following the spec correctly, but when comparing the rendered component with bullet and an small icon (16px) they seem to have almost the same height:

![Screenshot 2022-10-20 at 15 36 49](https://user-images.githubusercontent.com/44420072/196964495-07374c1d-aba4-475f-967d-77354d4e5787.png)

Of course the icon can be 6px height inside a 16px... I was checking the icon bookmark used in the catalog preview and the height of the icon inside the 16px box is ≈14px. 

I tried proportionally scaling the Figma definition to the screenshot size and the bullet still seems smaller: 

![Screenshot 2022-10-20 at 15 51 28](https://user-images.githubusercontent.com/44420072/196967976-dccc3ebe-1e12-4ade-968c-19b948fa0a25.png)

In addition, even though the neutralHigh is specified as the bullet color, it's not working as expected in dark mode:
 
![Screenshot 2022-10-20 at 16 16 23](https://user-images.githubusercontent.com/44420072/196973723-bf8e5e96-febc-44d3-b481-6acdc35e02ed.png)

```
let neutralHigh = MovistarColors.palette.grey6 | MovistarColors.palette.grey2
```

The `palette.grey2` color should be `#eeeeee` but it doesn't seems to be the color displayed...

2022-10-20 15:37 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/Fragments/List/ListFragmentView.swift
> +            rowView.addGestureRecognizer(itemTapGesture)
Sad we are using a tap gesture. This works like a button so it would been nice to have some feedback on press.

2022-10-20 15:43 UTC, jmpg93 commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +        stackView.systemLayoutSizeFitting(
I can't reproduce this bug. How did you exactly do it??

2022-10-20 15:48 UTC, alejandroruizponce approved these changes
Great work!

2022-10-20 15:58 UTC, amegias approved these changes

2022-10-20 15:58 UTC, amegias commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/ActionRow.swift
> +        spacing = 16
is there any spacing between actions??
![Captura de Pantalla 2022-10-20 a las 16 26 02](https://user-images.githubusercontent.com/9945756/196998954-8ef094d9-3856-485a-a559-124952dc0fb3.png)

![Captura de Pantalla 2022-10-20 a las 17 58 13](https://user-images.githubusercontent.com/9945756/196999174-72f1de2d-a9b6-451e-9fdf-9b02248e55be.png)

2022-10-20 16:15 UTC, jmbrocal commented
Hi folks!

I have to update the PR with
- Adding support for changing the background row while it is pressed (it is now defined in the spec)
- Fixing some ui issues

2022-10-20 16:16 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/ActionRow.swift
> +        spacing = 16
I noticed this bug, the PR was updated

2022-10-20 16:20 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/InformativeRow.swift
> +            imageView.image = UIImage.circle(diameter: 6, color: .neutralHigh)
Hey!

About the bullet icon: I am not using an asset, I am drawing it from code. I was using a diameter of 6 (i think it is the size in figma) but I will fix to use a diameter of 14. it is ok or it should be 16?

about the color in dark move, I will review it

2022-10-21 08:23 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/Fragments/List/Rows/InformativeRow.swift
> +            imageView.image = UIImage.circle(diameter: 6, color: .neutralHigh)
Talked about his in private. Fixed both cases. Ty!

2022-10-21 08:24 UTC, jmbrocal commented
More fixes, the last one I hope...

Add bullet icon

2022-10-21 08:26 UTC, jmbrocal commented on Sources/Mistica/Components/Sheet/View/SheetViewController.swift
> +        stackView.systemLayoutSizeFitting(
It is already fixed (but I have not idea how I fixed it XD)

2022-10-21 08:28 UTC, jmbrocal commented on Sources/Mistica/Utils/UIKitPreviewProvider/ViewPreview.swift
> +struct ViewPreview: UIViewRepresentable {
Ups, not needed. I used it while implementing the new rows (so I can use the SwiftUI Previews) but we cannot use this bc we must support iOS 13. Removing!

2022-10-21 08:36 UTC, jmpg93 approved these changes

2022-10-21 08:42 UTC, amegias approved these changes

2022-10-21 09:32 UTC, alejandroruizponce approved these changes

2022-10-21 09:55 UTC, aweell commented
It seems that the informative `list-item` label and the actions label are not using the correct text-preset, both should use `.textPreset3(weight: .regular)` causing those texts to render even bigger than the sheet title.

It can be compared with the single selection that is using the correct `font-size`.

From the specs:

* Informative list text-presets
![Screenshot 2022-10-21 at 11 53 38](https://user-images.githubusercontent.com/44420072/197168341-184b8c41-e5ea-4f7b-89cf-4692c116c7e0.png)

* Actions list text-presets
![Screenshot 2022-10-21 at 11 53 46](https://user-images.githubusercontent.com/44420072/197168312-be747f46-4e3a-4ee0-83ee-c62332f3694a.png)

2022-10-21 11:12 UTC, jmbrocal commented
> It seems that the informative `list-item` label and the actions label are not using the correct text-preset, both should use `.textPreset3(weight: .regular)` causing those texts to render even bigger than the sheet title.
> 
> It can be compared with the single selection that is using the correct `font-size`.
> 
> From the specs:
> 
> * Informative list text-presets
>   ![Screenshot 2022-10-21 at 11 53 38](https://user-images.githubusercontent.com/44420072/197168341-184b8c41-e5ea-4f7b-89cf-4692c116c7e0.png)
> * Actions list text-presets
>   ![Screenshot 2022-10-21 at 11 53 46](https://user-images.githubusercontent.com/44420072/197168312-be747f46-4e3a-4ee0-83ee-c62332f3694a.png)

good catch, the font was missing for that row. fixed

2022-10-21 11:23 UTC, merged

2022-10-21 11:25 UTC, tuentisre commented
:tada: This PR is included in version 18.3.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v18.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: