IOS-7914 Fix the brand token to return movistarBlue in dark mode in m…
Telefonica/mistica-ios pull request #243
Opened 2023-02-06 11:34 UTC by idenjoe

Hi!!

This PR is a fix for Brand token in MovES color palette for dark mode.

2023-02-08 14:41 UTC, cbarcom approved these changes

2023-02-09 13:56 UTC, jmpg93 approved these changes

2023-02-09 16:29 UTC, MontseTelefonica requested changes
<img width="428" alt="image" src="https://user-images.githubusercontent.com/95479574/217876467-f82ed728-98ad-4e0a-a79f-8e221d6e21c5.png">
La tag inactive parece que tiene un background más claro que el resto. ¿podéis revisar?

2023-02-09 16:38 UTC, MontseTelefonica commented
Corrección: el error en el fondo de los tags es de Mistica y ya está reportado para cambiarse.

2023-02-10 08:50 UTC, MontseTelefonica approved these changes
All good, Mistica will update the bg color of inactive tag to solve this problem.

2023-02-10 09:06 UTC, merged

2023-02-10 09:08 UTC, tuentisre commented
:tada: This PR is included in version 20.1.1 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v20.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: