IOS-8217 Add Brandeable FontWeights
Telefonica/mistica-ios pull request #267
Opened 2023-03-31 08:55 UTC by alejandroruizponce

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-8217

## 🥅 **What's the goal?**
The problem is that we are currently not handling correctly the different FontWeights (bold, medium, light...) that each brand has for each TextPreset we use. In a brand like Movistar the weight for TextPreset5 can be bold but for O2 it can be light. We have to handle it appropriately as we already do with colors or assets.

## 🚧 **How do we do it?**
For them we have proposed the following approach that you can see documented in Confluence where we explain the steps followed to handle the different types of FontWeights that currently exist in Design and that we must be able to handle from Mistica:

https://confluence.tid.es/display/CTO/%5BiOS%5D+Mistica+Brandeable+Font+Weights

## 🧪 **How can I verify this?**
You can load from Mistica Catalog the brand you want by setting it in AppDelegate and see the differences with the rest of the brands in their FontWeights.

2023-04-04 09:49 UTC, amegias commented on Sources/MisticaCommon/Fonts/MisticaFontWeights.swift
> +public enum FontWeightTypable {
```suggestion
/// Available font weights in Mistica
public enum MisticaFontWeightType {
```

Wdyt?? it's just a set of the allowed weights which will be mapped from the preset ones
https://github.com/Telefonica/mistica-ios/blob/df2b875d290ebf890a28435fb52dbb43755d1d5b/Sources/MisticaCommon/Fonts/FontStyle%2BWeights.swift#L27-L31

and finally mapped to the UIKit weights:
https://github.com/Telefonica/mistica-ios/blob/df2b875d290ebf890a28435fb52dbb43755d1d5b/Sources/MisticaCommon/Fonts/MisticaFontWeights.swift#L28-L39

2023-04-04 09:58 UTC, amegias approved these changes
Really good work!!!

2023-04-04 14:04 UTC, cbarcom approved these changes

2023-04-05 08:57 UTC, AnaMontes11 approved these changes
Nice job!

2023-04-10 09:26 UTC, alejandroruizponce commented on Sources/MisticaCommon/Fonts/MisticaFontWeights.swift
> +public enum FontWeightTypable {
Okey, tbh I wasn't sure with the naming, I like your idea. Fixed!

2023-04-11 07:50 UTC, pbartolome commented
I don't think most of these tests will need updates, are you sure you are running those using x86_64/Rosseta? also I see some images that have been updated with Spanish text (E.g Contactos instead of Contacts)

2023-04-11 09:49 UTC, amegias commented on Sources/MisticaCommon/Fonts/FontStyle+Weights.swift
> +        case light, regular, medium, branded
Talked with the Design Team, it will be finally a custom case for CardTitle label so it shouldn't be considered as a `.branded` textPreset4

2023-04-11 15:30 UTC, amegias commented
https://github.com/Telefonica/mistica-ios/blob/252092366a03bd3886417a1055853f4bd6caba90/MisticaCatalog/Source/FontsView.swift#L15-L20

now, it's not right at all :)
I would remove "bold"

2023-04-12 15:39 UTC, amegias requested changes

2023-04-12 15:39 UTC, amegias commented on Sources/MisticaCommon/Fonts/FontStyle+Weights.swift
> +    public var textPreset10: MisticaFontWeightType = .regular
I think you take the incoming new Vivo brand.

```suggestion
    public var textPreset5: MisticaFontWeightType = .light
    public var textPreset6: MisticaFontWeightType = .light
    public var textPreset7: MisticaFontWeightType = .light
    public var textPreset8: MisticaFontWeightType = .light
    public var textPreset9: MisticaFontWeightType = .light
    public var textPreset10: MisticaFontWeightType = .light
```

2023-04-12 15:52 UTC, alejandroruizponce commented on Sources/MisticaCommon/Fonts/FontStyle+Weights.swift
> +    public var textPreset10: MisticaFontWeightType = .regular
Fixed!

2023-04-12 16:04 UTC, amegias approved these changes

2023-04-13 04:58 UTC, alexanegon approved these changes

2023-04-13 07:37 UTC, pbartolome approved these changes

2023-04-18 14:05 UTC, merged

2023-04-18 14:06 UTC, tuentisre commented
:tada: This PR is included in version 23.2.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v23.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: