New custom feedback type
Telefonica/mistica-ios pull request #273
Opened 2023-05-04 09:33 UTC by pbartolome

## 🎟️ **Jira ticket**
[IOS-8360](https://jira.tid.es/browse/IOS-8360)

## 🥅 **What's the goal?**
Design has a fourth type of feedback which is not implemented on iOS. This `feedback` type, is similar to the other ones, but support any custom icon:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2429905/236166499-b9194937-7024-48e6-bfb5-483235b3cfba.png)

## 🚧 **How do we do it?**
- Create a new enum case `.feedback(icon)` to define this new type of feedback. As the image is something that only this new type can change, I've added as part of the enum case instead of adding it in the `FeedbackConfiguration` struct.
- Add tests
- Update doc

2023-05-04 09:39 UTC, amegias commented on Sources/Mistica/Components/Feedback/README.md
>  | Success     | Informative     | Error     |
1. what about adding an example of Feedback?
2. Check the explanation below if it needs to be changed
> All styles, if presented modally, will show a 'close' button. If they are presented with a push, a back button will show up except when the style is `success`. In that case the actions should dismiss this screen.

2023-05-04 09:51 UTC, amegias commented on Sources/MisticaSwiftUI/Components/Feedback/README.md
>  | Success     | Informative     | Error     |
see my comment above

2023-05-04 09:52 UTC, amegias requested changes

2023-05-04 09:52 UTC, amegias commented on Tests/MisticaTests/UI/FeedbackTests.swift
> +        isRecording = true
<img src="https://media0.giphy.com/media/YO7P8VC7nlQlO/giphy.gif"/>

2023-05-04 10:03 UTC, pbartolome commented on Sources/Mistica/Components/Feedback/FeedbackStyle+Toolkit.swift
> +            return nil
I have asked design about this, I would open another question in the public channel

2023-05-04 10:09 UTC, amegias approved these changes
Maybe we should evaluate to use only the SwiftUI component having a bridge (UIHostingVC) which returns a UIKit version:
- Remove duplicated doc
- Remove duplicated tests (screenshots -> size)
Anyway, out of scope.

Good work, Pablo!

2023-05-04 11:12 UTC, alexanegon approved these changes

2023-05-05 08:09 UTC, merged

2023-05-05 08:15 UTC, tuentisre commented
:tada: This PR is included in version 23.5.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v23.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: