IOS-9146: BottomSheet actions
Telefonica/mistica-ios pull request #299
Opened 2023-08-17 08:59 UTC by WanaldinoTelefonica

## 🎟️ **Jira ticket**
[IOS-9146](https://jira.tid.es/browse/IOS-9146)
This pull request is brach based from [IOS-9080](https://github.com/Telefonica/mistica-ios/pull/294) which is still waiting to be merged first

## 🥅 **What's the goal?**
- We need to include a new type of sheet: Actions
- This new category means renaming the current "Actions" to "Action List".
- We also took the opportunity to include a small restyling in this component (for better visualization you can see these updates marked in red in the specifications within anatomy and text) but they are the following:
    - Title -> text-preset-5
    - Subtitle -> text-preset-3
    - Draggable area height -> 32px
    - The padding between the text content and the interactive content becomes 8px.
    - Action height in Action list type -> 72px

## 🚧 **How do we do it?**
- Rename action into actionlist for all models
- Create a new model for new actions
- Update some styles

## 🧪 **How can I verify this?**
![Simulator Screenshot - iPhone 14 Pro - 2023-08-17 at 10 53 15](https://github.com/Telefonica/mistica-ios/assets/139126842/b266fb00-f6b6-47f2-9459-f8a9538c8ba0)

## 🏑 **AppCenter build**

2023-08-18 08:58 UTC, amegias commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +                    )
I would add a secondary and a link actions to have a complete example. WDYT?

2023-08-18 08:59 UTC, amegias commented on Sources/Mistica/Components/Sheet/Model/SheetConfiguration.swift
>              return false
maybe we can merge those cases which return false like:
case .a, .b, ...:
return false

2023-08-18 09:01 UTC, WanaldinoTelefonica commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogSheetViewController.swift
> +                    )
Ok. I'll add it for a better testing

2023-08-18 09:04 UTC, amegias commented on Tests/MisticaTests/UI/SheetTests.swift
> +        assertSnapshotForAllBrandsAndStyles(
do we need to test it in all of our brands? I would avoid it since it generates a lot of snapshots and only the palette changes :/ (which is not a good place to test it IMO)

2023-08-18 09:06 UTC, amegias commented on Tests/MisticaTests/UI/SheetTests.swift
>          assertSnapshotForAllBrandsAndStyles(
as I commented below, I think we don't need to test it in every brand. We can save a lot of snapshots which tests other system (color palettes). WDYT?

2023-08-18 09:13 UTC, WanaldinoTelefonica commented on Tests/MisticaTests/UI/SheetTests.swift
>          assertSnapshotForAllBrandsAndStyles(
This is just a rename of an old test to match with the correct naming

2023-08-18 09:41 UTC, DavidMarinCalleja commented on Tests/MisticaTests/UI/__Snapshots__/SheetTests/testSingleAction.1.png
there are two weird vertical lines around the button. Is it expected?

2023-08-18 09:44 UTC, WanaldinoTelefonica commented on Tests/MisticaTests/UI/__Snapshots__/SheetTests/testSingleAction.1.png
Yes as it comes from the Button component that shows like that. Maybe is something only happens on screenshots

2023-08-18 09:50 UTC, amegias commented on Tests/MisticaTests/UI/__Snapshots__/SheetTests/testSingleAction.1.png
yes, it's something weird that @idenjoe already faced 🤔

2023-08-18 09:56 UTC, DavidMarinCalleja commented on Tests/MisticaTests/UI/__Snapshots__/SheetTests/testActions.1.png
these files also have a vertical line around the buttons

2023-08-18 10:00 UTC, DavidMarinCalleja submitted a review, later dismissed
check why there are some vertical lines that appear in [some screenshots](https://github.com/Telefonica/mistica-ios/pull/299/files#diff-133a26079e2688e6f4d4a8e5b76c28ee2153907137239322bd02ecde44762d89):

![Screenshot 2023-08-18 at 12 00 07](https://github.com/Telefonica/mistica-ios/assets/1004932/996e2f98-93ed-4ba2-9ba9-c42867375c74)

2023-08-22 21:41 UTC, yceballost commented
Missing designers in this PR! And please, generate a new version for Mística Catalog for test the new component

2023-08-30 07:25 UTC, WanaldinoTelefonica commented on Tests/MisticaTests/UI/__Snapshots__/SheetTests/testSingleAction.1.png
I have created a new [JIRA task](https://jira.tid.es/browse/IOS-9281) for this.

2023-08-30 13:00 UTC, AnaMontes11 requested changes

2023-08-31 10:47 UTC, AnaMontes11 approved these changes
Nice job!

2023-08-31 11:21 UTC, merged

2023-08-31 11:24 UTC, tuentisre commented
:tada: This PR is included in version 26.0.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v26.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: