feat(Button): Add link danger button
Telefonica/mistica-ios pull request #359
Opened 2024-04-16 08:07 UTC by Gomay88

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-9508

## 🥅 **What's the goal?**
Add text link danger to Mistica and tests

## 🚧 **How do we do it?**
Create the linkDanger button so we can use it in the rest of projects

2024-04-16 10:40 UTC, dhidalgofadrique approved these changes
Good job! 👍

2024-04-17 13:16 UTC, DavidMarinCalleja approved these changes
<img src="https://media2.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-medium.gif"/>

2024-04-18 14:17 UTC, yceballost requested changes
Can yo

2024-04-18 14:17 UTC, yceballost commented on Tests/MisticaSwiftUITests/UI/__Snapshots__/ButtonTests/testRegularSizeWithLinkDangerStyle.1.png
Can you generate a version of mistica catalog to check on it?

2024-04-18 14:17 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Button/MisticaButtonStyle.swift
> +                        backgroundColor: .buttonLinkBackgroundSelected,
should be `buttonLinkDangerBackgroundSelected`?

2024-04-18 14:17 UTC, yceballost commented on Tests/MisticaSwiftUITests/UI/__Snapshots__/ButtonTests/testRegularSizeWithLinkDangerStyle.1.png
will the inverse version not be included?
![image](https://github.com/Telefonica/mistica-ios/assets/6722153/2e9734bc-663e-41a8-a082-3b8b558f140c)

2024-04-18 14:20 UTC, yceballost commented on Tests/MisticaSwiftUITests/UI/__Snapshots__/ButtonTests/testRegularSizeWithLinkDangerStyle.1.png
Missing dark mode screenshot

2024-04-18 18:37 UTC, yceballost requested changes

2024-04-18 18:37 UTC, yceballost commented on Tests/MisticaTests/UI/__Snapshots__/ButtonTests/testRegularSizeWithLinkDangerInverseStyle.with-blau-dark-style.png
sorry for being picky, but can you use `.background` color as background in screenshots? (instead of transparent)  By this way is easy to see what is dark mode and light (and obviously is more easy to know if the color is correct or not)

2024-04-19 08:02 UTC, Gomay88 commented on Tests/MisticaTests/UI/__Snapshots__/ButtonTests/testRegularSizeWithLinkDangerInverseStyle.with-blau-dark-style.png
We are testing the button with the background needed we can't change it because if we change the background color for any reason tests will fail and that's not what we want :(. BTW you can have a look at them in the Mistica app: https://install.appcenter.ms/orgs/Tuenti-Organization/apps/Mistica-SwiftUI-iOS

2024-04-19 09:09 UTC, Gomay88 commented on Tests/MisticaTests/UI/__Snapshots__/ButtonTests/testRegularSizeWithLinkDangerInverseStyle.with-blau-dark-style.png
Sorry!! Try with this one -> https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-swiftui-ios/distribution_groups/public/releases/56

2024-04-22 07:16 UTC, merged

2024-04-22 09:00 UTC, tuentisre commented
:tada: This PR is included in version 29.10.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v29.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: