IOS-10010 Add new type for Gradients support in brands
Telefonica/mistica-ios pull request #361
Opened 2024-04-22 11:17 UTC by alejandroruizponce

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-10010

## 🥅 **What's the goal?**
Following the previous PR (https://github.com/Telefonica/mistica-ios/pull/358) where we introduced the new O2New brand, changes are required to support color tokens that instead of colors can be gradients indistinctly for the different brands. For that reason it's necessary to create a new supertype that can be color or gradient for a given token.

## 🚧 **How do we do it?**
In order to carry out this new implementation, the following important changes have been made:
- An enumerated has been created to act as a supertype called `MisticaColorStyle` that can be color or gradient. The gradient type will receive a `MisticaGradient` that has been defined according to what has been agreed with Design regarding the json that we will receive with the gradient data: https://github.com/Telefonica/mistica-design/blob/production/tokens/o2-new.json
- The two tokens affected at this moment by this supertype are only `backgroundBrand` and `backgroundContainerBrand`, and only in O2New its value is gradient type, in the rest of brands its value will remain color type.
- To be able to use the supertype in any view of our Mistica components it is necessary to create helpers that allow us both in UIKit and SwiftUI to receive a token type `MisticaColorStyle` and assign it to that view to decide whether to apply a color or a gradient to the background of the same.
- These helpers will use as base a `GradientView` **created exclusively in SwiftUI, the reason is that in UIKit the gradient generated differs from SwiftUI, its rendering is different, less progressive and therefore less similar to the one we want to achieve, which is a gradient similar to the web one.**
- Therefore for UIKit it is necessary to generate a UIViewController that contains a UIHostingController to encapsulate the SwiftUI `GradientView`. 
 - The Mistica components affected by this new supertype have been `Feedback`, `Header` and `List` cells. Several fixes had to be made so that the view generated by the UIHostingController would not give problems when configuring it in each view, which could be **a UIView or a UIStackView, or even a view cell. The solution must be valid for all views**.

## 🧪 **How can I verify this?**
From the Mistica Catalog **by choosing the O2New brand in the brand selector** it is possible to test the gradients on the following components:
- Feedback (.success type only)
- Header (Inverse style only)
- List (Inverse layout style only)

Demo test:

<img src="https://github.com/Telefonica/mistica-ios/assets/23401607/df6efbcc-f0a0-40db-91a3-a3370a9f73e1" width="300">

2024-04-22 11:19 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogFeedbacksViewController.swift
> +            //navigationController.navigationBar.applyMisticaStyle()
PENDING ISSUE HERE. Currently the Feedback component depends on a navigation bar whose color is separate from the background of the Feedback itself and should match so as not to break the UI of the Feedback. The problem is that it is not possible to define a gradient in two parts, one in the navigationBar and another in the Feedback. Design should decide what to do in this case.

2024-04-22 11:22 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/ButtonCatalogView.swift
> -                    .listRowBackground(style.inverse ? Color.backgroundBrand : Color.background)
This kind of backgrounds for Catalog or DEBUG tasks do not need to be backgroundBrand since they involve us using the helpers here and complicate the code for something that has no impact on production.

2024-04-22 11:23 UTC, alejandroruizponce commented on Sources/Mistica/Components/Header/HeaderView.swift
>          topStackView.removeArrangedSubviews()
When adding a subview in a UIStackView it is necessary to move to the front the arrenged subviews that we have so that they are not behind the gradient.

2024-04-22 11:26 UTC, alejandroruizponce commented on Sources/MisticaCommon/Components/GradientView+UIKit.swift
> +    convenience public init(rootView: Content, ignoreSafeArea: Bool) {
**WHY IS THIS NECESSARY?** Unfortunately I don't see any way to collide with the safe areas when adding GradientView in a full screen view such as Feedback. If we don't indicate to avoid the safe areas we are left with a blank space on the edges that I don't see any other way to avoid.

It cannot be put by default since for cases like the UIStackView of the Header or the own cells of List we would break the UI if we also ignore the safe areas there.

2024-04-22 11:27 UTC, alejandroruizponce commented on Sources/MisticaCommon/Components/GradientView.swift
> +    func gradientPoints(size: CGSize, cssAngle: CGFloat) -> (start: UnitPoint, end: UnitPoint) {
This function is intended to receive the same points that would be received on the Web using CSS from a given angle.

2024-04-22 13:07 UTC, amegias requested changes

2024-04-22 13:07 UTC, amegias commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogFeedbacksViewController.swift
> +            navigationController.navigationBar.isHidden = true
????

2024-04-22 13:15 UTC, amegias commented on Sources/MisticaCommon/Components/GradientView+UIKit.swift
> +                .constraint(equalTo: view.centerYAnchor),
are those two needed?

2024-04-22 13:17 UTC, amegias commented on Sources/MisticaCommon/Components/GradientView.swift
> +    func gradientPoints(size: CGSize, cssAngle: CGFloat) -> (start: UnitPoint, end: UnitPoint) {
I would add doc to this class explaining why we are using this view:
- to allow dark/light mode automatically

2024-04-22 13:18 UTC, amegias commented on Sources/MisticaCommon/Components/GradientView.swift
> +public struct GradientView: View {
I would add doc to this class explaining why we are using this view:
- to allow dark/light mode automatically

```suggestion
/// ...
public struct GradientView: View {
```

2024-04-22 13:19 UTC, amegias commented on Sources/MisticaCommon/Components/GradientView+UIKit.swift
> +public class GradientSwiftUIViewController: UIViewController {
I would add a comment here to explain why you should use this hosting VC
```suggestion
/// ...
public class GradientSwiftUIViewController: UIViewController {
```

2024-04-22 13:21 UTC, amegias commented on Sources/MisticaCommon/Colors/MisticaColorStyle.swift
> +}
needed? why?

2024-04-22 13:38 UTC, amegias commented on Sources/MisticaCommon/Components/GradientView+UIKit.swift
> +    convenience public init(rootView: Content, ignoreSafeArea: Bool) {
I would explain it in the code to avoid forgetting this

2024-04-22 14:46 UTC, alejandroruizponce commented on MisticaCatalog/Source/Catalog/Mistica/Components/UICatalogFeedbacksViewController.swift
> +            navigationController.navigationBar.isHidden = true
Originally it was commented to see if the navigation bar was configured correctly or if it should be removed. Currently the color of the nav bar matches the background of the view so there is no difference that breaks the UI with the gradient. So these lines have been restaured.

2024-04-22 14:47 UTC, amegias commented on Sources/Mistica/Utils/Extensions/UIView+Utils.swift
> +    public func addLinearGradient(colors: [UIColor], locations: [CGFloat], angle: CGFloat, ignoreSafeArea: Bool) {
why don't you pass a `Gradient` var plus `ignoreSafeArea` var?

2024-04-22 14:47 UTC, alejandroruizponce commented on Sources/Mistica/Utils/Extensions/UIView+Utils.swift
> +    public func applyLinearGradient(colors: [UIColor], locations: [CGFloat], angle: CGFloat, ignoreSafeArea: Bool) {
Yes, it's more accurated. Renamed.

2024-04-22 14:49 UTC, alejandroruizponce commented on Sources/MisticaCommon/Components/GradientView.swift
> +public struct GradientView: View {
Doc added in GradientSwifUIViewController, it's really which is gonna use this SwiftUI view.

2024-04-22 14:51 UTC, alejandroruizponce commented on Sources/MisticaCommon/Colors/MisticaColorStyle.swift
> +}
As before we used extensions for UIColor and Color, this way we can directly instantiate backgroundBrand for a variable of type MisticaColor, like this one:
```
    var backgroundColor: MisticaColor {
        switch self {
        case .fullWidth:
            return .solid(.background)
        case .boxed:
            return .solid(.backgroundContainer)
        case .boxedInverse:
            return .backgroundBrand
        }
    }
```

2024-04-22 14:52 UTC, alejandroruizponce commented on Sources/MisticaCommon/Colors/MisticaColorStyle.swift
> +}
I'm more convinced by the second option, renamed!

2024-04-22 14:59 UTC, alejandroruizponce commented on Sources/Mistica/Utils/Extensions/UIView+Utils.swift
> +    public func addLinearGradient(colors: [UIColor], locations: [CGFloat], angle: CGFloat, ignoreSafeArea: Bool) {
Well, I thought about it for the same reason that I have separated the addLinearGradient function from setMisticaColor, in case at some point we use the addLinearGradient func from another part of the app where we do not receive a Gradient object and the values are assigned manually. Maybe it won't happen. WDYT?

2024-04-23 08:29 UTC, amegias commented on Sources/Mistica/Utils/Extensions/UIView+Utils.swift
> +    public func addLinearGradient(colors: [UIColor], locations: [CGFloat], angle: CGFloat, ignoreSafeArea: Bool) {
I have a no strong opinion here :/
I would take care of the current code, if you feel that passing a `Gradient` the current code will look better... go ahead

2024-04-23 15:09 UTC, amegias approved these changes
<img src="https://media2.giphy.com/media/r7Ql3VIg4x6WA/giphy.gif"/>

2024-04-23 15:32 UTC, alejandroruizponce commented on Sources/MisticaCommon/Colors/MisticaGradient.swift
> +    public let colors: [UIColor]
Mm, but it's agreed with Design that this is the structure to follow. What would be the point if we had more colors than stops? Or vice versa? The gradient could not be applied correctly. I think this is a mandatory of the gradient structure, it should always be respected IMHO.

2024-04-24 07:16 UTC, idenjoe approved these changes

2024-04-24 14:39 UTC, merged