Ios 10314-include custom fonts in mistica catalog app
Telefonica/mistica-ios pull request #376
Opened 2024-06-28 09:22 UTC by L-Trujillo26

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-10314

## 🥅 **What's the goal?**
Include custom fonts (Vivo & OnAir) in Mistica Catalog app.

## 🚧 **How do we do it?**

Adding the fonts to the Mystica Catalog app and setting the FontStyle to match the selected brand's font.

## 🧪 **How can I verify this?**
The font changes to the selected brand: Vivo New, O2, or Movistar.

2024-06-28 11:29 UTC, amegias commented on MisticaCatalog/Source/MisticaCatalogApp.swift
> +        case .o2, .movistar:
`.o2New` is missing

2024-06-28 11:29 UTC, amegias commented on MisticaCatalog/Source/MisticaCatalogApp.swift
> +        case .o2, .movistar:
`.o2New` is missing

2024-06-28 11:30 UTC, amegias commented on MisticaCatalog/Source/MisticaCatalogApp.swift
> +        default:
Consider to avoid using `default`. Then if we add a new brand in the future, it will be forced to put that new brand in some case ;)

2024-06-28 11:30 UTC, amegias commented on MisticaCatalog/Source/MisticaCatalogApp.swift
> +        default:
Consider to avoid using `default`. Then if we add a new brand in the future, it will be forced to put that new brand in some case ;)

2024-07-01 16:07 UTC, amegias approved these changes

2024-07-01 18:56 UTC, yceballost requested changes
Can we include Telefónica Sans to use it in Telefónica and TU skin?

2024-07-02 06:32 UTC, dhidalgofadrique approved these changes
Good job! 👍

2024-07-05 09:52 UTC, L-Trujillo26 commented
> Can we include Telefónica Sans to use it in Telefónica and TU skin?

done!

2024-07-05 10:40 UTC, dhidalgofadrique commented on MisticaCatalog/Source/Common/Extensions/BrandStyle+FontMapping.swift
> +                boldFont: "OnAir-Bold",
Isn't this `OnAir-Bold` font missing in `MisticaCatalog/Resources/` and in the Info.plist `UIAppFonts` property?

2024-07-05 10:50 UTC, yceballost requested changes

2024-07-05 10:50 UTC, yceballost commented on MisticaCatalog/Resources/Telefonica Sans Bold.otf
Please, use DemiBold instead of Bold font weight

2024-07-05 10:50 UTC, yceballost commented on MisticaCatalog/Source/MisticaCatalogApp.swift
When you run the app, by the default is not showing On Air font, when you change the skin through the tabs it is when the font changes. (you need swap to other brand and go back to Movistar if you want to see On Air in Movistar skin)

2024-07-05 13:23 UTC, L-Trujillo26 commented on MisticaCatalog/Resources/Telefonica Sans Bold.otf
I followed the documentation from Mistica's readme for the implementation of the Telefonica font.
https://github.com/Telefonica/mistica-ios/tree/main/Sources/MisticaCommon/Fonts

However, the brand documentation indicates, as you mentioned, using DemiBold, but it also indicates using Medium. In which cases should I choose the different font types?
<img width="767" alt="Captura de pantalla 2024-07-05 a las 14 01 48" src="https://github.com/Telefonica/mistica-ios/assets/53877180/3ad47957-343d-404b-b27c-d8d439397e84">

https://brandfactory.telefonica.com/document/483#/nuestra-identidad-visual/tipografia

2024-07-05 13:54 UTC, amegias approved these changes

2024-07-05 14:27 UTC, L-Trujillo26 commented on MisticaCatalog/Resources/Telefonica Sans Bold.otf
Done! updated
 https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-swiftui-ios/distribution_groups/public

2024-07-11 10:09 UTC, yceballost approved these changes
Nice! 🤩 Thanks!!

2024-07-12 10:39 UTC, merged

2024-07-12 10:50 UTC, tuentisre commented
:tada: This PR is included in version 31.0.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v31.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: