feat(PosterCard): LATCH-2313 Poster card component
Telefonica/mistica-ios pull request #413
Opened 2024-11-21 12:46 UTC by salavert

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/LATCH-2313

## 🥅 **What's the goal?**

Add Poster Card component

[Brand Factory documentation](https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/components/cards/poster-card):

Mistica UI & Template Kit:
https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/%F0%9F%94%B8-Cards-Specs?node-id=2085-6956&node-type=frame&t=RdDblTC9BxrtMADD-0 
https://www.figma.com/design/3iEvVzfHBtg3sROXBHzkn7/%F0%9F%94%B8-Image-%26-Video-Specs?node-id=0-1&node-type=canvas&t=rmv0XyAYfGhJIVsn-0 

[Playground](https://mistica-web.vercel.app/?path=/story/components-cards-postercard--default)

## 🧪 **How can I verify this?**

Mistica Catalog:
https://github.com/user-attachments/assets/97d58b8e-84e4-45a2-ae88-14996749bc1b

In use at Latch:
https://github.com/user-attachments/assets/8368d931-fb62-48b7-8476-4ea2cd88af85

2024-11-21 12:59 UTC, salavert commented on MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/PosterCardCatalogView.swift
> +                    URL(string: "https://www.apple.com/105/media/us/ipad/2024/45762adb-901a-4726-8b0c-1f3ee092b09a/anim/welcome-hero/xlarge.mp4")!,
One is under 5s and the other is a longer one so we can test the loading process and pause/play button

2024-11-21 12:59 UTC, salavert commented on README.md
See it live https://github.com/Telefonica/mistica-ios/tree/edfb84f45cf73168650f0a63c80f2d6a590248c7/Sources/MisticaSwiftUI/Components/Cards#postercard

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +        parameters.autoplay && videoPlayerDuration >= Constants.minVideoPlayerDurationToShowControls
As said on specs, pause control button will appear only if video is above 5s

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +                    posterImage
Poster image will appear while loading video

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +                    }
Will autoplay if scroll visibility % is met

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +                    misticaColorView(.backgroundBrand)
I've checked that in case of O2 we shown correctly a gradient color

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +                Color.promo
I couldn't find specs about promo exact tonality, high? low? other?

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +                    .padding(Constants.spacing * 2)
As said before, video controls appear only if duration > 5s.
This restriction does not apply to the loading icon.

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCardVideoPlayer.swift
> +public struct PosterCardVideoPlayer: UIViewRepresentable {
This is a wrapper for AVPlayer so we avoid showing native back/forth/play/pause buttons

2024-11-21 12:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/README.md
> +## PosterCard
https://github.com/Telefonica/mistica-ios/tree/edfb84f45cf73168650f0a63c80f2d6a590248c7/Sources/MisticaSwiftUI/Components/Cards#postercard

2024-11-25 06:17 UTC, DavidMarinCalleja commented on Sources/MisticaSwiftUI/Components/Cards/README.md
> +    image: image
I have not seen the `image` parameter I think it is `slots`. isn't it?
```suggestion
    slot: image
```

2024-11-25 06:31 UTC, DavidMarinCalleja commented on MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/PosterCardCatalogView.swift
> +                    URL(string: "https://www.apple.com/105/media/us/ipad/2024/45762adb-901a-4726-8b0c-1f3ee092b09a/anim/welcome-hero/xlarge.mp4")!,
If the first video is already downloaded I would use that in the catalog as the second URL could change or Apple could delete it.

2024-11-25 06:46 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/README.md
> +    image: image
Fixed

2024-11-25 06:46 UTC, salavert commented on MisticaCatalog/Source/Catalog/MisticaSwiftUI/Components/PosterCardCatalogView.swift
> +                    URL(string: "https://www.apple.com/105/media/us/ipad/2024/45762adb-901a-4726-8b0c-1f3ee092b09a/anim/welcome-hero/xlarge.mp4")!,
Fixed

2024-11-25 14:12 UTC, DavidMarinCalleja approved these changes
<img src="https://media0.giphy.com/media/3o6fIZjpzcGBzwaayc/giphy.gif"/>

2024-11-25 15:43 UTC, yceballost requested changes

2024-11-25 15:43 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +            .background(Color.backgroundContainer)
I'm not sure if this background is for the "circle" of top actions, but:
Use `inverse` instead of `backgroundContainer` and include opacity

![image](https://github.com/user-attachments/assets/55577595-a3c3-4496-b15f-ed2ca5a69f12)

https://www.figma.com/design/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=3949-8933&t=GNIE0twITWlOrI6F-4

2024-11-25 15:43 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Texts are overflowing
![IMG_5381](https://github.com/user-attachments/assets/1e28b2fd-ca03-46f1-86ba-0ebf8488a9f0)

2024-11-25 15:43 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
the images are deformed across different aspect ratio
![Screenshot 2024-11-25 at 16 40 00 jpeg](https://github.com/user-attachments/assets/a73bb14b-db50-4d8d-ae25-5fd1841b35ac)

2024-11-25 15:43 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
I miss the interaction throughout the card 🤔 is it implemented? should have an option in the catalog?

2024-11-26 07:09 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Do you mean the top action buttons?
![Screenshot 2024-11-26 at 08 09 30](https://github.com/user-attachments/assets/2a437e0c-f681-485b-9bf0-77d0baedba4e)

2024-11-26 10:09 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Nope! interaction when pressing the entire card

Example:
https://tinyurl.com/2a54mrcs

2024-11-26 11:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Fixed  https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public/releases/273

![multi-lines](https://github.com/user-attachments/assets/83f84580-c7f6-4201-94a3-eef24c9b75d2)

2024-11-26 11:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Fixed https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public/releases/273

<img width="1297" alt="Screenshot 2024-11-26 at 11 31 05" src="https://github.com/user-attachments/assets/413456d5-0050-4fdd-a2e3-069561c992de">

2024-11-26 11:59 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Fixed, I've added the interaction https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public/releases/273

The new Catalog now allows you to add an asset as well

![postercard-asset](https://github.com/user-attachments/assets/46863759-3856-46ad-a285-ed6d57d90e50)

2024-11-26 20:45 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
mmm the interaction is not behave like are specified, please checkout this artboard
https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/%F0%9F%94%B8-Cards-Specs?node-id=2386-8777&t=S2ZitoyuZycmEePs-4

I tested but the card turns "white" and flashy

2024-11-26 20:49 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +            .background(Color.backgroundContainer)
nice! 

A little detail, could you include a bigger area for the touch area? To cover accessibility we need to ensure 48x48
![image](https://github.com/user-attachments/assets/61bd3c1f-9f7b-471b-85ba-46a0d0f2758a)

2024-11-26 20:50 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +            .background(Color.backgroundContainer)
I detected a problem in dark mode, the Top Action icons change to "white" but these icons should be always in "black"  (#000)

![image](https://github.com/user-attachments/assets/e7d61370-a25d-4985-8980-85b7ed6a8348)

2024-11-27 09:33 UTC, alejandroruizponce approved these changes
Good work!!

2024-11-27 16:25 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
Fixed
https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public/releases/275

Example of Poster Card at Latch
https://github.com/user-attachments/assets/5d312290-9123-4352-a994-d79fe7b9539f

2024-11-27 16:26 UTC, salavert commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +            .background(Color.backgroundContainer)
Fixed, now it's always black
https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-ios/distribution_groups/public/releases/275

2024-11-28 19:43 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
perfect!!

2024-11-28 19:43 UTC, yceballost commented on Sources/MisticaSwiftUI/Components/Cards/PosterCard/PosterCard.swift
> +            .background(Color.backgroundContainer)
nice!! thanks a lot

2024-11-28 19:44 UTC, yceballost approved these changes
great! 🥰

2024-11-29 06:42 UTC, merged

2024-11-29 06:44 UTC, tuentisre commented
:tada: This PR is included in version 33.3.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v33.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: