IOS-10800 Make ViewStates component in SwiftUI
Telefonica/mistica-ios pull request #415
Opened 2024-11-28 15:53 UTC by alejandroruizponce

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-10800

## 🥅 **What's the goal?**
As a performance objective to make SwiftUI components, ViewStates component will be migrated from UIKit to SwiftUI.

## 🚧 **How do we do it?**
A new component similar to the component in UIKit has been created and added inside the Catalog.

There is a difference between the buttons we have for SwiftUI and the UIKit buttons, I'm not clear which one should be the correct one since I can't find references to the Design of this component. I hope that in the revision of this PR a member of Design can clarify it.

If the SwiftUI design is correct, it could be used as a base and apply in UIKit a wrapper that encapsulates the SwiftUI design to use the same design in all platforms.

## 🧪 **How can I verify this?**
| SwiftUI | UIKit |
|---|---|
| <img width="330" alt="Screenshot 2023-10-03 at 15 27 29" src="https://github.com/user-attachments/assets/71890627-ea37-4664-9374-abf03a199f86"> |<img width="330" alt="Screenshot 2023-10-03 at 15 30 48" src="https://github.com/user-attachments/assets/37cf2275-23b8-4b09-9152-59498abebddf">|

## 🏑 **AppCenter build**
Generating...

2024-12-02 06:18 UTC, DavidMarinCalleja requested changes
There would be a missing test for this component, wouldn't there?

2024-12-03 10:03 UTC, alejandroruizponce commented
> Hi @alejandroruizponce , Here’s the link to the button component specifications from Mística: [Buttons component Specs](https://www.figma.com/design/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0-1085&t=ax5v29e42Sl4h6j7-4). You can review it to clarify any doubts and make the necessary adjustments. Let me know if this helps or if you need anything else. :)

Thanks @AnaMontes11, but really my question is more about what type of button is correct for this View State component. If the one we use in UIKit or the SwiftUI one, or if both are valid.

2024-12-03 10:04 UTC, alejandroruizponce commented
> There would be a missing test for this component, wouldn't there?

There were no tests for the component in UIKit either, if I can I will check and add some.

2024-12-03 15:10 UTC, AnaMontes11 commented
Hi @alejandroruizponce, this is not a Mística component; I understand it comes from an old View State. On our side, it doesn’t matter if you use a small or large button, although for consistency, it’s better to use the same one in both. If this decision is relevant for Novum or could affect something in production, we’d need to discuss it with the product team. Let me know if I’ve clarified your question.

2024-12-04 06:28 UTC, DavidMarinCalleja approved these changes

2024-12-09 10:50 UTC, AnaMontes11 commented
Hello again, @alejandroruizponce As I mentioned, it seems like an older empty state. If it helps, I would use the same (large) button in the SwiftUI version for consistency and discuss with the team updating both to something closer to a more modern empty state.

2024-12-13 11:23 UTC, franciscojrp approved these changes

2024-12-16 13:11 UTC, alejandroruizponce commented
> Hello again, @alejandroruizponce As I mentioned, it seems like an older empty state. If it helps, I would use the same (large) button in the SwiftUI version for consistency and discuss with the team updating both to something closer to a more modern empty state.

Talked with @AnaMontes11 and @aweell, same large button will be used on both platforms even though they are different right now. The unification of the button can be looked at in a different ticket as well as the update of the texts:
https://jira.tid.es/browse/IOS-10849

2024-12-16 13:45 UTC, merged

2024-12-16 13:46 UTC, tuentisre commented
:tada: This PR is included in version 33.7.0 :tada:

The release is available on [GitHub release](https://github.com/Telefonica/mistica-ios/releases/tag/v33.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: